name: env_282PJ
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
dependencies:
  - python=3.9
  - pytorch
  - pip
  - pip:
    - jupyter==1.0.0
    - matplotlib==3.8.4
    - numpy==1.26.4
    - pandas==2.2.1
    - scikit-learn==1.4.1.post1
    - seaborn==0.13.2
    - tqdm==4.66.2
    - transformers==4.17.0
    - wandb==0.22.3
    - xgboost==1.6.1
    - protobuf==3.20.1
    - omegaconf==2.3.0
    - munch==4.0.0
